import Head from 'next/head'
import { Octokit } from 'octokit'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import parseData from '@/utils/parseData'
import { CommitInfo } from '@/utils/interfaces'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Git Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Git Tracker</main>
    </>
  )
}

export async function getServerSideProps() {
  const octokit = new Octokit({
    auth: process.env.GITHUB_ACCESS_TOKEN,
  })
  const response = await octokit.request(
    'GET /repos/ragomez7/git-tracker/commits',
    {},
  )
  const commits = response.data.map(
    (commitInfo: CommitInfo) => commitInfo.commit,
  )
  const parsedCommits = parseData(commits)
  return { props: { parsedCommits } }
}
